import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Head from 'next/head'
import NavBar from "./NavBar";

const mont = Montserrat({ 
  subsets: ['latin'],
  variable: "--font-mont"
})
export const metadata: Metadata = {
  title: 'StoreApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={`${mont.variable} font-mont bg-cream`}>
        
        <NavBar/>
        <main className='bg-cream'>{children}</main>
      </body>
    </html>
  )
}
